data_root: "/home/fisa/stockage1/mindscan"

fps: 120
window_sec: 2.0
stride_sec: 1.0
purity: 0.8

train_subjects: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
val_subjects:   [21,22,23,24]
test_subjects:  [25,26,27,28,29,30,31,32]

num_classes: 31

batch_size: 128
epochs: 30
lr: 0.001
dropout: 0.2
seed: 42

wandb:
  project: "data_challenge"
  run_name: "cnn1d-skeleton"